"""update db: add SN in logAna

Revision ID: 225058c11bf
Revises: 2409186df50
Create Date: 2017-03-22 21:32:46.362585

"""

# revision identifiers, used by Alembic.
revision = '225058c11bf'
down_revision = '2409186df50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loganalyzers', sa.Column('SN_id', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loganalyzers', 'SN_id')
    ### end Alembic commands ###
