"""update db: add SN in logAna

Revision ID: 2409186df50
Revises: 4f160644695
Create Date: 2017-03-22 21:28:36.857149

"""

# revision identifiers, used by Alembic.
revision = '2409186df50'
down_revision = '4f160644695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
