"""modify LogAnalyzer again.

Revision ID: 396ce835f1b
Revises: None
Create Date: 2017-02-27 01:26:02.937659

"""

# revision identifiers, used by Alembic.
revision = '396ce835f1b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.String(length=128), nullable=True),
    sa.Column('emac', sa.String(length=128), nullable=True),
    sa.Column('wmac', sa.String(length=128), nullable=True),
    sa.Column('bmac', sa.String(length=128), nullable=True),
    sa.Column('addr', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_timestamp', 'customers', ['timestamp'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('bugtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bugtypes_timestamp', 'bugtypes', ['timestamp'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kw_regex', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('test_flag', sa.Boolean(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bugtype_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bugtype_id'], ['bugtypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keywords_kw_regex', 'keywords', ['kw_regex'], unique=True)
    op.create_index('ix_keywords_timestamp', 'keywords', ['timestamp'], unique=False)
    op.create_table('loganalyzers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ftp_url', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bug_id', sa.Integer(), nullable=True),
    sa.Column('moc_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('tv_model', sa.String(length=128), nullable=True),
    sa.Column('log_dir', sa.String(length=128), nullable=True),
    sa.Column('ftp_dl_ok', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('bugtype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bugtype_id'], ['bugtypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loganalyzers_ftp_url', 'loganalyzers', ['ftp_url'], unique=True)
    op.create_index('ix_loganalyzers_timestamp', 'loganalyzers', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loganalyzers_timestamp', 'loganalyzers')
    op.drop_index('ix_loganalyzers_ftp_url', 'loganalyzers')
    op.drop_table('loganalyzers')
    op.drop_index('ix_keywords_timestamp', 'keywords')
    op.drop_index('ix_keywords_kw_regex', 'keywords')
    op.drop_table('keywords')
    op.drop_index('ix_posts_timestamp', 'posts')
    op.drop_table('posts')
    op.drop_index('ix_bugtypes_timestamp', 'bugtypes')
    op.drop_table('bugtypes')
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    op.drop_index('ix_roles_default', 'roles')
    op.drop_table('roles')
    op.drop_index('ix_customers_timestamp', 'customers')
    op.drop_table('customers')
    ### end Alembic commands ###
