"""update db

Revision ID: 4f160644695
Revises: 5366c8856d5
Create Date: 2017-03-19 16:49:45.370207

"""

# revision identifiers, used by Alembic.
revision = '4f160644695'
down_revision = '5366c8856d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
